# [build]
# command = "npm start"

# [[redirects]]
# from = "/api/*"
# status = 200
# to = "/api/:splat"

# [[headers]]
# for = ""
# [headers.values]
# Access-Control-Allow-Origin = "https://healthyfoodpage.netlify.app/"

[build]
command = "npm run start"
publish = "src"

# Configuración de redirecciones y proxies para API
[[redirects]]
# Redirecciona cualquier solicitud a la raíz de tu sitio web a la ruta "/api"
from = "/*"
status = 200
to = "/api/:splat"

[[redirects]]
# Redirecciona cualquier solicitud a la ruta "/api/*" a la ruta "/.netlify/functions/server/*"
from = "/api/*"
status = 200
to = "/.netlify/functions/server/:splat"

# Configuración de proxy para las solicitudes entrantes a la ruta "/.netlify/functions/server/*"
[[redirects]]
force = true
from = "/.netlify/functions/server/*"
status = 200
to = "http://localhost:4200/:splat"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
