[build]
publish = "/"
command = "npm start" 
functions = "src/routes"


[[redirects]]
from = "/*"
status = 200
to = "src/index.html"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
