# [build]
# base="/"
# publish="src"
# command="npm start"
# functions="src/routes"
# [build.processing]
#     skip_processing = false
# [build.processing.css]
#     bundle = true
#     minify = false
# [build.processing.js]
#     bundle = true
#     minify = false
# [build.processing.html]
#     pretty_urls = true
# [build.processing.images]
#     compress = true

# [[redirects]]
# from = "/*"
# to = "/api/recetas/:splat"

# [[redirects]]
# from = "/*"
# to = "/index.html"
# status = 200