[build]
command = "npm start"

[[redirects]]
from = "/api/*"
status = 200
to = "/api/:splat"

[[headers]]
for = ""
[headers.values]
Access-Control-Allow-Origin = "https://healthyfoodpage.netlify.app/"